/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopproject;

/**
 *
 * @author zubi1
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deletestudentjButton = new javax.swing.JButton();
        AddstudentjButton2 = new javax.swing.JButton();
        viewstudentjButton3 = new javax.swing.JButton();
        SearchstudentjButton3 = new javax.swing.JButton();
        updatecredentialsjButton4 = new javax.swing.JButton();
        updatestudentjButton5 = new javax.swing.JButton();
        viewcomplainjButton4 = new javax.swing.JButton();
        calculatebilljButton6 = new javax.swing.JButton();
        exitjButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(520, 200));

        deletestudentjButton.setBackground(new java.awt.Color(102, 102, 255));
        deletestudentjButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deletestudentjButton.setForeground(new java.awt.Color(242, 242, 242));
        deletestudentjButton.setText("Delete a Student");
        deletestudentjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletestudentjButtonActionPerformed(evt);
            }
        });

        AddstudentjButton2.setBackground(new java.awt.Color(102, 102, 255));
        AddstudentjButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddstudentjButton2.setForeground(new java.awt.Color(242, 242, 242));
        AddstudentjButton2.setText("Add a Student");
        AddstudentjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddstudentjButton2ActionPerformed(evt);
            }
        });

        viewstudentjButton3.setBackground(new java.awt.Color(102, 102, 255));
        viewstudentjButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewstudentjButton3.setForeground(new java.awt.Color(242, 242, 242));
        viewstudentjButton3.setText("View a Student");
        viewstudentjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewstudentjButton3ActionPerformed(evt);
            }
        });

        SearchstudentjButton3.setBackground(new java.awt.Color(102, 102, 255));
        SearchstudentjButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SearchstudentjButton3.setForeground(new java.awt.Color(242, 242, 242));
        SearchstudentjButton3.setText("Search a Student");
        SearchstudentjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchstudentjButton3ActionPerformed(evt);
            }
        });

        updatecredentialsjButton4.setBackground(new java.awt.Color(102, 102, 255));
        updatecredentialsjButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updatecredentialsjButton4.setForeground(new java.awt.Color(242, 242, 242));
        updatecredentialsjButton4.setText("Update credientials");
        updatecredentialsjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatecredentialsjButton4ActionPerformed(evt);
            }
        });

        updatestudentjButton5.setBackground(new java.awt.Color(102, 102, 255));
        updatestudentjButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updatestudentjButton5.setForeground(new java.awt.Color(242, 242, 242));
        updatestudentjButton5.setText("Update student");
        updatestudentjButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatestudentjButton5ActionPerformed(evt);
            }
        });

        viewcomplainjButton4.setBackground(new java.awt.Color(102, 102, 255));
        viewcomplainjButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewcomplainjButton4.setForeground(new java.awt.Color(242, 242, 242));
        viewcomplainjButton4.setText("View Complains");
        viewcomplainjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcomplainjButton4ActionPerformed(evt);
            }
        });

        calculatebilljButton6.setBackground(new java.awt.Color(102, 102, 255));
        calculatebilljButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        calculatebilljButton6.setForeground(new java.awt.Color(242, 242, 242));
        calculatebilljButton6.setText("Calculate Bill");
        calculatebilljButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatebilljButton6ActionPerformed(evt);
            }
        });

        exitjButton7.setBackground(new java.awt.Color(102, 102, 255));
        exitjButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exitjButton7.setForeground(new java.awt.Color(242, 242, 242));
        exitjButton7.setText("Exit");
        exitjButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitjButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SearchstudentjButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddstudentjButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(viewcomplainjButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(updatecredentialsjButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(deletestudentjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calculatebilljButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(viewstudentjButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(updatestudentjButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitjButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viewstudentjButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deletestudentjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AddstudentjButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updatestudentjButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updatecredentialsjButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SearchstudentjButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(calculatebilljButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addComponent(exitjButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(viewcomplainjButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchstudentjButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        searchstudent s1 = new searchstudent();
        dispose();
        s1.setVisible(true);
    }

    private void viewcomplainjButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        ShowComplains s1 = new ShowComplains();
        dispose();
        s1.setVisible(true);
    }

    private void AddstudentjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddstudentjButton2ActionPerformed
        
        StudentFrame1 f1 = new StudentFrame1();
        dispose();
        f1.setVisible(true);
    }//GEN-LAST:event_AddstudentjButton2ActionPerformed

    private void exitjButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitjButton7ActionPerformed
        
        LoginFram l1  = new LoginFram();
        dispose();
        l1.setVisible(true);
    }//GEN-LAST:event_exitjButton7ActionPerformed

    private void deletestudentjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletestudentjButtonActionPerformed
        
        DeleteStudent d1 = new DeleteStudent();
        dispose();
        d1.setVisible(true);
    }//GEN-LAST:event_deletestudentjButtonActionPerformed

    private void updatecredentialsjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatecredentialsjButton4ActionPerformed
        
        UpdateCredentials u1 = new UpdateCredentials();
        dispose();
        u1.setVisible(true);
    }//GEN-LAST:event_updatecredentialsjButton4ActionPerformed

    private void updatestudentjButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatestudentjButton5ActionPerformed
        
        UpdateStudentFrame f1 = new UpdateStudentFrame();
        dispose();
        f1.setVisible(true);
    }//GEN-LAST:event_updatestudentjButton5ActionPerformed

    private void calculatebilljButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatebilljButton6ActionPerformed
        FeeSearch f1 = new FeeSearch();
        dispose();
        f1.setVisible(true);
    }//GEN-LAST:event_calculatebilljButton6ActionPerformed

    private void viewstudentjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewstudentjButton3ActionPerformed
        
        ShowStudent s1 = new ShowStudent();
        dispose();
        s1.setVisible(true);
    }//GEN-LAST:event_viewstudentjButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddstudentjButton2;
    private javax.swing.JButton SearchstudentjButton3;
    private javax.swing.JButton calculatebilljButton6;
    private javax.swing.JButton deletestudentjButton;
    private javax.swing.JButton exitjButton7;
    private javax.swing.JButton updatecredentialsjButton4;
    private javax.swing.JButton updatestudentjButton5;
    private javax.swing.JButton viewcomplainjButton4;
    private javax.swing.JButton viewstudentjButton3;
    // End of variables declaration//GEN-END:variables
}
