/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopproject;

import javax.swing.JOptionPane;

/**
 *
 * @author zubi1
 */
public class OldStudentFrame extends javax.swing.JFrame {

    /**
     * Creates new form OldStudentFrame
     */
    public OldStudentFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewprofilejButton1 = new javax.swing.JButton();
        updateprofilejButton2 = new javax.swing.JButton();
        checkfeejButton3 = new javax.swing.JButton();
        leavehosteljButton4 = new javax.swing.JButton();
        addcomplainjButton5 = new javax.swing.JButton();
        viewmenujButton6 = new javax.swing.JButton();
        homejButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(520, 200));

        viewprofilejButton1.setText("view profile");
        viewprofilejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewprofilejButton1ActionPerformed(evt);
            }
        });

        updateprofilejButton2.setText("Update profile");
        updateprofilejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateprofilejButton2ActionPerformed(evt);
            }
        });

        checkfeejButton3.setText("Check fee");
        checkfeejButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkfeejButton3ActionPerformed(evt);
            }
        });

        leavehosteljButton4.setText("Leave Hostel");
        leavehosteljButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leavehosteljButton4ActionPerformed(evt);
            }
        });

        addcomplainjButton5.setText(" Add Complain");
        addcomplainjButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcomplainjButton5ActionPerformed(evt);
            }
        });

        viewmenujButton6.setText(" View Menu");
        viewmenujButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewmenujButton6ActionPerformed(evt);
            }
        });

        homejButton7.setText("Home");
        homejButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homejButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewprofilejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateprofilejButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkfeejButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(homejButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(leavehosteljButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addcomplainjButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewmenujButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewprofilejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateprofilejButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkfeejButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leavehosteljButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addcomplainjButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewmenujButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(homejButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewprofilejButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        ViewProfileSearch profile = new ViewProfileSearch();
        dispose();
        profile.setVisible(true);
    }

    private void updateprofilejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateprofilejButton2ActionPerformed
       
        OldStudentUpdateFrame old1 = new OldStudentUpdateFrame();
        dispose();
        old1.setVisible(true);
    }//GEN-LAST:event_updateprofilejButton2ActionPerformed

    private void checkfeejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkfeejButton3ActionPerformed
        OldStudentFeeCheck fee = new OldStudentFeeCheck();
        dispose();
        fee.setVisible(true); 
    }//GEN-LAST:event_checkfeejButton3ActionPerformed

    private void leavehosteljButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leavehosteljButton4ActionPerformed
        DeleteOldStudent delete = new DeleteOldStudent();
        dispose();
        delete.setVisible(true);
    }//GEN-LAST:event_leavehosteljButton4ActionPerformed

    private void addcomplainjButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcomplainjButton5ActionPerformed
       
        ComplainFrame c1 = new ComplainFrame();
        dispose();
        c1.setVisible(true);
    }//GEN-LAST:event_addcomplainjButton5ActionPerformed

    private void viewmenujButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                                 
       Menu m1 = new Menu();
       
       JOptionPane.showMessageDialog(null, m1.printMenu(),"Mess Menu",1);
    }

    private void homejButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homejButton7ActionPerformed
       
        StartingFrame s1 = new StartingFrame();
        s1.setVisible(true);
        dispose();
    }//GEN-LAST:event_homejButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OldStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OldStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OldStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OldStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OldStudentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcomplainjButton5;
    private javax.swing.JButton checkfeejButton3;
    private javax.swing.JButton homejButton7;
    private javax.swing.JButton leavehosteljButton4;
    private javax.swing.JButton updateprofilejButton2;
    private javax.swing.JButton viewmenujButton6;
    private javax.swing.JButton viewprofilejButton1;
    // End of variables declaration//GEN-END:variables
}
